#pragma once


// Store.cpp 
#define BIG_STORE_RADIUS 100
#define	SMALL_STORE_RADIUS 60
#define BIG_STORE_RENT 30
#define SMALL_STORE_RENT 7


// Deployer.cpp
#define GRID_SPACING 10
#define POPULATION_SIZE 200
#define INIT_STORES_NUM 5
#define GENERATIONS_NUM 50
#define LOCATION_MUTATION_RATIO 0.05
#define TYPE_MUTATION_RATIO 0.05
#define DISPLACMENT_RATE 30


